# Cloudflare Pages Configuration
name = "seo-health-check-tool"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages Functions Configuration
[build]
command = "echo 'No build required for static site'"
publish = "."

# Environment Variables (configure in Cloudflare Dashboard)
[env.production.vars]
# Set PAGESPEED_API_KEY in Cloudflare Pages dashboard under Settings > Environment variables

[env.preview.vars]
# Preview environment variables (optional)